/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import edu.sit.cs.db.CSDbDelegate;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Oriopun AI
 */
public class Login extends PopUp {

    //public static CSDbDelegate in = new CSDbDelegate("csprog-in.sit.kmutt.ac.th", "3306", "CSC105_G3", 
        //"csc105_2014", "csc105");
    
    public static int pass;
    public static String user; 
    public static ConnectDB db = new ConnectDB();
    public static CSDbDelegate get = db.getConnect();
    
    /**
     * Creates new form Receipt
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loginbtn = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        UserField = new javax.swing.JTextField();
        Cancelbtn = new javax.swing.JButton();
        BG_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loginbtn.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        Loginbtn.setText("Login");
        Loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbtnMouseClicked(evt);
            }
        });
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 70, -1));

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 160, 30));

        UserField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 30));

        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        BG_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/login.png"))); // NOI18N
        getContentPane().add(BG_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_buttomActionPerformed
        // TODO add your handling code here:
        System.out.println(get.disconnect()); //when push exit buttom
        System.exit(0); //close java frame loei
    }//GEN-LAST:event_Exit_buttomActionPerformed

    private void Login_buttomActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_buttomActionPerformed(evt);
            }
        });        // TODO add your handling code here:

    }//GEN-LAST:event_LoginbtnActionPerformed

    private void Exit_buttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_buttomActionPerformed(evt);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseClicked
        // TODO add your handling code here:
        String user = UserField.getText();
        int pass = Integer.parseInt(PasswordField.getText());
        checkPassword(user + "", pass);
    }//GEN-LAST:event_LoginbtnMouseClicked

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        System.out.println(get.disconnect()); //when push exit buttom
        System.exit(0); //close java frame loei
    }//GEN-LAST:event_CancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println(get.connect());
                new Login().setVisible(true);
            }
        });
    }
    
    public void checkPassword(String user, int pass) {
        //String output = "";
        String sql = "SELECT * FROM ATMuser ";
        ArrayList<HashMap> list = get.queryRows(sql);
        boolean checkSuccess = get.executeQuery(sql);
        System.out.println(checkSuccess);

        for (HashMap a : list) { // create a for รองรับ hashmap list
            if (a.get("Username").equals(user)) { //login
                this.user = user;
                if (a.get("Password").equals("" + pass)) { // password colu
                    this.pass = Integer.parseInt(String.valueOf(a.get("Password")));
                    JOptionPane.showMessageDialog(null , "Login Successfully!");
                    Transaction t = new Transaction();
                    //t.no = Integer.parseInt(String.valueOf(a.get("A/C No.")));
                    t.setVisible(true);
                    setVisible(false);
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Password!","Wrong Password", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
            JOptionPane.showMessageDialog(null, "Please Register","No Account",JOptionPane.ERROR_MESSAGE);
            break;
        }
    }
    
    public static int getPass(){
        return Login.pass;
    }
    
    public static String getUser(){
        return Login.user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_login;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserField;
    // End of variables declaration//GEN-END:variables
}
